### ISSUE TITLE
Changing instance type fails with minimal information as to why

### ISSUE THREAD

**Issue by skoloCFD** [aws/elastic-beanstalk-roadmap#309]
I am having issues changing the instanceType of an EB environment. This happens if I try to change the instance family, for example to c7i, c7i-flex, or m7a.

I can understand if these instance types are simply not supported. In that case, it would be nice to have some messaging explaining that, and a place where I could check which instance types **are** available. One idea I had, was that this message was coming from the instance type not being available in the selected AZ, but I changed the configuration to accept all three subnets in the AWS region, and still got the same error below:

`Updating Auto Scaling launch configuration named: awseb-e-BLABLABLA-stack-AWSEBAutoScalingLaunchConfiguration-BLABLABLA failed Reason: Resource handler returned message: "The specified instance type m7a.large is not valid (Service: AutoScaling, Status Code: 400, Request ID: BLABLABLA)" (RequestToken: BLABLABLA, HandlerErrorCode: InvalidRequest)`

The version is Python 3.11 running on 64bit Amazon Linux 2023/4.0.0

**Comment by matthewdouglas** [comment]
@skoloCFD What region are you in? `c7i-flex` isn't a real instance type, but maybe you meant `m7i-flex`. 

c7i, m7i, and m7a aren't available in all regions. In North America, they should be in all except `us-west-1` or `ca-central-1`. There may be availability for these types in `eu-west-1` also.

**Comment by skoloCFD** [comment]
Sorry, forgot to mention that this occurred in eu-west-1. In that region there are plenty of c7i and m7a instances available - I launched one of each of this type outside of eb to verify.

**Comment by MADDY312** [comment]
I am trying to switch from t2.small to c7a.medium/m7a.medium, It throws the same error, but when trying to switch from t2.small to c5a.large, it works fine. And my region is us-east-1. Has anybody found any solution to this?

**Comment by sprite2005** [comment]
Having the same issue tried to switch to c7i.xlarge

**Comment by MADDY312** [comment]
I fixed it by making IMDSv1 "activated" 
![ndnd](https://github.com/aws/elastic-beanstalk-roadmap/assets/81014149/d5354fd0-7fa6-4683-8ed4-c84f3f082470)

**Comment by skoloCFD** [comment]
This is still occurring, with or without IMDSv1 Activated:

```failed Reason: Resource handler returned message: "The specified instance type m7i.large is not valid```

This is despite using supported instance types, at least according to:

```aws elasticbeanstalk describe-configuration-options --options="Namespace=aws:ec2:instances,OptionName=InstanceTypes"```

**Comment by dakotawashok** [comment]
I can confirm that I got this error today when trying to update an Elastic Beanstalk Environment configuration value for the instance size to `c7i.large`.

**Comment by petervanwylen** [comment]
Yes, I'm getting the same problem with c7i and c7a

**Comment by petervanwylen** [comment]
Happens even when creating a new environment. It's not just a problem when updating existing envs.

**Comment by teledemic** [comment]
I tried on both windows and linux platforms - disabling IMDSv1 is what finally let things work for me
