### ISSUE TITLE
I cannot get my Django app to deploy on the new Python platform.

### ISSUE THREAD

**Issue by chkur** [aws/elastic-beanstalk-roadmap#68]
I cannot get my Django app to deploy on the new Python platform. Running the command `python manage.py collectstatic --noinput` fails, both in the old config file style and in the new `.platform/hooks/predeploy/collectstatic.sh` setup.

Either way Django is not being found as a Python package, as if the virtual environment has not beed activated. Do we now have to activate the virtual environment first?

_Originally posted by @digicase in https://github.com/aws/elastic-beanstalk-roadmap/issues/15#issuecomment-619572349_

**Comment by chkur** [comment]
I wanted to migrate python app from Amazon Linux 1 to Amazon Linux 2 to remove some deploy workarounds. But now I need to write new workarounds for simple virtualenv activating. **container_commands** section is useless for python apps. At least - correct docs please, don't mislead people.

**Comment by digicase** [comment]
@chkur here's the code I have that works, in the file ./platform/hooks/predeploy/collect_static.sh

The `collect_static.sh ` file needs the correct permissions, which is stated in the docs. The rest I had to work out myself and with the help of other commenters on issue #15 

```bash
#!/bin/bash
source /var/app/venv/*/bin/activate
export PYTHONPATH=/var/app/staging
export DJANGO_SETTINGS_MODULE=config.settings.production
django-admin collectstatic --noinput --clear
```

**Comment by chkur** [comment]
@digicase thanks for reply.
I hope developers will fix python platform and/or docs. It looks like it's still beta state.

**Comment by matandro** [comment]
The logging on this is really bad too, the only reason I noticed is because it crashed from a python 2.7 on a python 3.7 environment. I would have probably missed it even if it was from the main python3. There needs to be something showing the underlying error from the command output.

Any way, another workaround is `command: source /var/app/venv/*/bin/activate && python SCRIPT_TO_RUN`. I tried activating at the first command but it gets deactivated every command.

I think the best way to fix it and allow behaviors outside the environment (I don't see the use case but...) is to add a flag (like leader_only) that allows you to choose if you want to work outside the environment.

**Comment by Sekhar-Kutikuppala** [comment]
Thank you for the feedback. we are working on this issue.

**Comment by hcNick** [comment]
I had a similar issue, not sure if it's related. When deploying with `requirements.txt`, EB generates the Pipfile and all the python libraries end up in `/var/app/venv/staging-LQM1lest/bin`. However if I use a Pipfile myself, then gunicorn, pip, setuptools ends up in  `/var/app/venv/staging-LQM1lest/bin` and everything else ends up in `/var/app/venv/requirements-neJltVej/bin`, which then gives the Django not found error.

**Comment by Sekhar-Kutikuppala** [comment]
We addressed this issue in the latest Python AL2 platform version - 64bit Amazon Linux 2 v3.1.0 running Python 3.7

**Comment by Raam124** [comment]
It's still not working always command not found. please update your docs to Linux 2 ASAP

**Comment by DataGreed** [comment]
Any update on this? The old platform is deprecated and I cannot migrate some projects because of this issue and lack of proper documentation

**Comment by chadamski** [comment]
Having issues with the lack of documentation on this, still.

**Comment by samueltc** [comment]
@chadamski @DataGreed 

in `.platform/hooks/postdeploy/10-collectstatic.sh`:

```
#!/usr/bin/env bash
cd /var/app/current
mkdir -p staticfiles
chown -R webapp:webapp staticfiles
$PYTHONPATH/python manage.py collectstatic
```
